import streamlit as st
from nltk import jaccard_distance
import openai
import streamlit as st
import os

# Autenticación de OpenAI (oculta la clave en una variable de entorno)
openai.api_key = os.environ.get("OPENAI_API_KEY")


def detect_gpt3(prompt):
    completions = openai.Completion.create(
        engine="text-davinci-003",
        prompt=prompt,
        max_tokens=2048,
        n=10,
        stop=None,
        temperature=0.5,
    )

    generated_texts = [choice.text for choice in completions.choices]
    similarity_scores = []
    for generated_text in generated_texts:
        similarity_scores.append(1-jaccard_distance(set(prompt.split()), set(generated_text.split())))
    return max(similarity_scores)

st.title("GPT-3 Text Detection App")

text = st.text_area("Enter text to check if generated by GPT-3:")

if st.button("Check"):
    threshold = 0.8
    result = detect_gpt3(text)
    if result > threshold:
        st.success("The text is generated by GPT-3")
    else:
        st.error("The text is not generated by GPT-3")


# Text to check
text = "The quick brown fox jumps over the lazy dog"

# Generate completions with GPT-3
completions = openai.Completion.create(
    engine="text-davinci-002",
    prompt=text,
    max_tokens=2048,
    n=10,
    stop=None,
    temperature=0.5,
)

# Get list of generated completions
generated_texts = [choice.text for choice in completions.choices]

# Compare generated completions with original text
similarity_scores = []
for generated_text in generated_texts:
    similarity_scores.append(openai.Davinci.compare(prompt=text, reference=generated_text))

# Check if the mean of the similarity scores is above a certain threshold
mean_similarity = sum(similarity_scores) / len(similarity_scores)
if mean_similarity > 0.8:
    print("The text is likely generated by GPT-3")
else:
    print("The text is not likely generated by GPT-3")
