import openai
import streamlit as st
import os

# Autenticación de OpenAI (oculta la clave en una variable de entorno)
openai.api_key = os.environ.get("OPENAI_API_KEY")

# Text to check
text = "The quick brown fox jumps over the lazy dog"

# Generate completions with GPT-3
completions = openai.Completion.create(
    engine="text-davinci-002",
    prompt=text,
    max_tokens=2048,
    n=10,
    stop=None,
    temperature=0.5,
)

# Get list of generated completions
generated_texts = [choice.text for choice in completions.choices]

# Compare generated completions with original text
similarity_scores = []
for generated_text in generated_texts:
    similarity_scores.append(openai.Davinci.compare(prompt=text, reference=generated_text))

# Check if the mean of the similarity scores is above a certain threshold
mean_similarity = sum(similarity_scores) / len(similarity_scores)
if mean_similarity > 0.8:
    print("The text is likely generated by GPT-3")
else:
    print("The text is not likely generated by GPT-3")
