import openai
import streamlit as st
import os

# Autenticación de OpenAI (oculta la clave en una variable de entorno)
openai.api_key = os.environ.get("OPENAI_API_KEY")

# Set the API key
openai.api_key = "your_api_key"

# Create a function that uses GPT-3 to generate text
def generate_text(prompt):
    completions = openai.Completion.create(engine="text-davinci-002", prompt=prompt, max_tokens=1024, n=1,stop=None,temperature=0.5)
    message = completions.choices[0].text
    return message.strip()

# Create a function to compare the input text and the generated text
def compare_text(input_text, generated_text):
    similarity = 0
    # Compare the input text and the generated text and calculate similarity
    # You can use some libraries like fuzzyset or others
    return similarity

def main():
    st.title("GPT-3 Text Detection")
    input_text = st.text_area("Enter the text you want to check")
    if input_text:
        generated_text = generate_text(input_text)
        similarity = compare_text(input_text, generated_text)
        if similarity > 0.8:
            st.success("The text is similar to a text generated by GPT-3")
        else:
            st.error("The text is not similar to a text generated by GPT-3")
    st.info("Note: The similarity is not a 100% guarantee that the text was written with GPT-3")

if __name__ == "__main__":
    main()
